name: Test

on: [push]

jobs:
    test:
        name: Test

        runs-on: ubuntu-latest

        strategy:
            matrix:
                php-version: ['7.3', '7.4', '8.0']

        steps:
            - name: Setup PHP ${{ matrix.php-version }}
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php-version }}

            - name: Checkout
              uses: actions/checkout@v2

            - name: Validate composer.json and composer.lock
              run: composer validate

            - name: Install dependencies
              run: composer install

            - name: Run test suite
              run: composer run-script test